# Generated by Django 4.2.7 on 2026-05-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('workspace', 'Workspace only'), ('private', 'Private')], default='workspace', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('developer', 'Developer'), ('manager', 'Manager'), ('owner', 'Owner'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('designer', 'Designer'), ('qa', 'QA'), ('product', 'Product'), ('hr', 'HR')], default='viewer', max_length=20),
        ),
    ]
