# Generated by Django 4.2.7 on 2026-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_notification_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('workspace_owner', 'Workspace Owner'), ('admin', 'Admin'), ('project_manager', 'Project Manager'), ('member', 'Member'), ('guest', 'Guest')], default='guest', max_length=20),
        ),
    ]
