# Generated by Django 4.2.7 on 2026-05-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('developer', 'Developer'), ('manager', 'Manager'), ('owner', 'Owner'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('designer', 'Designer'), ('qa', 'QA'), ('product', 'Product'), ('hr', 'HR')], default='viewer', max_length=20),
        ),
    ]
