# Generated by Django 4.2.7 on 2026-05-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_otp_enabled_remove_user_otp_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='notification_preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_visibility',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('workspace_owner', 'Workspace Owner'), ('admin', 'Admin'), ('project_manager', 'Project Manager'), ('member', 'Member'), ('guest', 'Guest'), ('developer', 'Developer'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('devops', 'DevOps'), ('designer', 'Designer'), ('qa', 'QA'), ('product', 'Product'), ('hr', 'HR')], default='guest', max_length=20),
        ),
    ]
