[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.11" # Dummy version to stop it from using 3.14
  NODE_VERSION = "20"

# This prevents Netlify from trying to install Python dependencies
[functions]
  node_bundler = "esbuild"
