openapi: 3.0.3
info:
  title: Remote Team Manager API
  version: 1.0.0
  description: Full REST API for managing remote teams.
paths:
  /api/auth/login/:
    post:
      operationId: auth_login_create
      tags:
      - auth
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/logout/:
    post:
      operationId: auth_logout_create
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/auth/me/:
    get:
      operationId: auth_me_retrieve
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    patch:
      operationId: auth_me_partial_update
      tags:
      - auth
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/auth/register/:
    post:
      operationId: auth_register_create
      tags:
      - auth
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/auth/token/refresh/:
    post:
      operationId: auth_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/workspaces/:
    get:
      operationId: workspaces_retrieve
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: workspaces_create
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/workspaces/{id}/:
    get:
      operationId: workspaces_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    patch:
      operationId: workspaces_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: workspaces_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/workspaces/{id}/members/:
    get:
      operationId: workspaces_members_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: workspaces_members_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/workspaces/{id}/members/{user_id}/:
    delete:
      operationId: workspaces_members_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: user_id
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/workspaces/{workspace_pk}/activity/:
    get:
      operationId: workspaces_activity_retrieve
      parameters:
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/workspaces/{workspace_pk}/projects/:
    get:
      operationId: workspaces_projects_retrieve
      parameters:
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: workspaces_projects_create
      parameters:
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/workspaces/{workspace_pk}/projects/{id}/:
    get:
      operationId: workspaces_projects_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    patch:
      operationId: workspaces_projects_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: workspaces_projects_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/workspaces/{workspace_pk}/projects/{project_pk}/tasks/:
    get:
      operationId: workspaces_projects_tasks_retrieve
      parameters:
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: workspaces_projects_tasks_create
      parameters:
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/workspaces/{workspace_pk}/projects/{project_pk}/tasks/{id}/:
    get:
      operationId: workspaces_projects_tasks_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    patch:
      operationId: workspaces_projects_tasks_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: workspaces_projects_tasks_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/workspaces/{workspace_pk}/projects/{project_pk}/tasks/{task_pk}/subtasks/:
    get:
      operationId: workspaces_projects_tasks_subtasks_retrieve
      parameters:
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: task_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: workspaces_projects_tasks_subtasks_create
      parameters:
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: task_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /api/workspaces/{workspace_pk}/projects/{project_pk}/tasks/{task_pk}/subtasks/{id}/:
    patch:
      operationId: workspaces_projects_tasks_subtasks_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: task_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    delete:
      operationId: workspaces_projects_tasks_subtasks_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: task_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/workspaces/{workspace_pk}/projects/{project_pk}/tasks/{task_pk}/timelogs/:
    get:
      operationId: workspaces_projects_tasks_timelogs_retrieve
      parameters:
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: task_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
    post:
      operationId: workspaces_projects_tasks_timelogs_create
      parameters:
      - in: path
        name: project_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: task_pk
        schema:
          type: string
          format: uuid
        required: true
      - in: path
        name: workspace_pk
        schema:
          type: string
          format: uuid
        required: true
      tags:
      - workspaces
      security:
      - jwtAuth: []
      responses:
        '200':
          description: No response body
components:
  schemas:
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
