# Generated by Django 4.2.7 on 2026-05-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
    ]
