# Generated by Django 4.2.7 on 2026-05-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
