# Generated by Django 4.2.7 on 2026-05-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_edited_at_message_is_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
