# Generated by Django 4.2.7 on 2026-05-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_channelmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('message_sent', 'Message Sent'), ('reaction_added', 'Reaction Added'), ('channel_created', 'Channel Created'), ('user_login', 'User Login'), ('workspace_switched', 'Workspace Switched')], max_length=30),
        ),
    ]
