# Generated by Django 4.2.7 on 2026-05-22 21:38
# Patched v5: one cursor.execute() per statement — psycopg2 guarantees each
# call executes exactly one SQL statement, regardless of psycopg2 version.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_chat_tables(apps, schema_editor):
    """
    Nuclear + idempotent: drop old tables, then create final schema.
    Each cursor.execute() call is a single SQL statement — no multiline
    ambiguity, no sqlparse dependency, works with every psycopg2 version.
    """
    conn = schema_editor.connection
    vendor = conn.vendor  # 'postgresql' or 'sqlite'

    with conn.cursor() as c:
        if vendor == 'postgresql':
            # ── Drop old tables (IF EXISTS = safe when table is missing) ────
            c.execute('DROP TABLE IF EXISTS "chat_messagereaction" CASCADE')
            c.execute('DROP TABLE IF EXISTS "chat_message" CASCADE')
            c.execute('DROP TABLE IF EXISTS "chat_channelmembership" CASCADE')
            c.execute('DROP TABLE IF EXISTS "chat_channel_members" CASCADE')
            c.execute('DROP TABLE IF EXISTS "chat_channel" CASCADE')
            c.execute('DROP TABLE IF EXISTS "chat_directmessage_participants" CASCADE')
            c.execute('DROP TABLE IF EXISTS "chat_directmessage" CASCADE')

            # ── Create ChatRoom ──────────────────────────────────────────────
            c.execute(
                'CREATE TABLE IF NOT EXISTS "chat_chatroom" ('
                '"id" bigserial NOT NULL PRIMARY KEY,'
                '"name" varchar(255) NULL,'
                '"room_type" varchar(20) NOT NULL DEFAULT \'group\','
                '"created_at" timestamptz NOT NULL DEFAULT now(),'
                '"workspace_id" bigint NULL'
                '  REFERENCES "workspaces_workspace"("id") DEFERRABLE INITIALLY DEFERRED'
                ')'
            )

            # ── Create participants M2M ──────────────────────────────────────
            c.execute(
                'CREATE TABLE IF NOT EXISTS "chat_chatroom_participants" ('
                '"id" bigserial NOT NULL PRIMARY KEY,'
                '"chatroom_id" bigint NOT NULL'
                '  REFERENCES "chat_chatroom"("id") DEFERRABLE INITIALLY DEFERRED,'
                '"user_id" bigint NOT NULL'
                '  REFERENCES "accounts_user"("id") DEFERRABLE INITIALLY DEFERRED,'
                'UNIQUE("chatroom_id","user_id")'
                ')'
            )

            # ── Create Message with final schema ─────────────────────────────
            c.execute(
                'CREATE TABLE IF NOT EXISTS "chat_message" ('
                '"id" bigserial NOT NULL PRIMARY KEY,'
                '"content" text NOT NULL,'
                '"created_at" timestamptz NOT NULL DEFAULT now(),'
                '"is_read" boolean NOT NULL DEFAULT false,'
                '"sender_id" bigint NOT NULL DEFAULT 1'
                '  REFERENCES "accounts_user"("id") DEFERRABLE INITIALLY DEFERRED,'
                '"room_id" bigint NOT NULL DEFAULT 1'
                '  REFERENCES "chat_chatroom"("id") DEFERRABLE INITIALLY DEFERRED'
                ')'
            )

        else:
            # ── SQLite (local dev / CI) ──────────────────────────────────────
            for tbl in [
                'chat_messagereaction', 'chat_message', 'chat_channelmembership',
                'chat_channel_members', 'chat_channel',
                'chat_directmessage_participants', 'chat_directmessage',
            ]:
                c.execute(f'DROP TABLE IF EXISTS "{tbl}"')

            c.execute(
                'CREATE TABLE IF NOT EXISTS "chat_chatroom" ('
                '"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,'
                '"name" varchar(255) NULL,'
                '"room_type" varchar(20) NOT NULL DEFAULT \'group\','
                '"created_at" datetime NOT NULL,'
                '"workspace_id" integer NULL REFERENCES "workspaces_workspace"("id")'
                ')'
            )
            c.execute(
                'CREATE TABLE IF NOT EXISTS "chat_chatroom_participants" ('
                '"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,'
                '"chatroom_id" integer NOT NULL REFERENCES "chat_chatroom"("id"),'
                '"user_id" integer NOT NULL REFERENCES "accounts_user"("id"),'
                'UNIQUE("chatroom_id","user_id")'
                ')'
            )
            c.execute(
                'CREATE TABLE IF NOT EXISTS "chat_message" ('
                '"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,'
                '"content" text NOT NULL,'
                '"created_at" datetime NOT NULL,'
                '"is_read" integer NOT NULL DEFAULT 0,'
                '"sender_id" integer NOT NULL DEFAULT 1 REFERENCES "accounts_user"("id"),'
                '"room_id" integer NOT NULL DEFAULT 1 REFERENCES "chat_chatroom"("id")'
                ')'
            )


def drop_chat_tables(apps, schema_editor):
    with schema_editor.connection.cursor() as c:
        for tbl in ['chat_message', 'chat_chatroom_participants', 'chat_chatroom']:
            c.execute(f'DROP TABLE IF EXISTS "{tbl}" CASCADE')


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(create_chat_tables, reverse_code=drop_chat_tables),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ChatRoom',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, max_length=255, null=True)),
                        ('room_type', models.CharField(
                            choices=[('private', 'Private'), ('group', 'Group'), ('workspace', 'Workspace')],
                            default='group', max_length=20,
                        )),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
                        ('workspace', models.ForeignKey(
                            blank=True, null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='chat_rooms',
                            to='workspaces.workspace',
                        )),
                    ],
                ),
                migrations.AlterUniqueTogether(name='channelmembership', unique_together=None),
                migrations.RemoveField(model_name='channelmembership', name='channel'),
                migrations.RemoveField(model_name='channelmembership', name='user'),
                migrations.RemoveField(model_name='directmessage', name='participants'),
                migrations.RemoveField(model_name='messagereaction', name='message'),
                migrations.RemoveField(model_name='messagereaction', name='user'),
                migrations.AlterModelOptions(name='message', options={'ordering': ['created_at']}),
                migrations.RemoveField(model_name='message', name='channel'),
                migrations.RemoveField(model_name='message', name='direct_message'),
                migrations.RemoveField(model_name='message', name='reply_to'),
                migrations.RemoveField(model_name='message', name='updated_at'),
                migrations.RemoveField(model_name='message', name='user'),
                migrations.AddField(
                    model_name='message',
                    name='is_read',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='message',
                    name='sender',
                    field=models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sent_messages',
                        to=settings.AUTH_USER_MODEL,
                    ),
                    preserve_default=False,
                ),
                migrations.DeleteModel(name='Channel'),
                migrations.DeleteModel(name='ChannelMembership'),
                migrations.DeleteModel(name='DirectMessage'),
                migrations.DeleteModel(name='MessageReaction'),
                migrations.AddField(
                    model_name='message',
                    name='room',
                    field=models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='chat.chatroom',
                    ),
                    preserve_default=False,
                ),
            ],
        ),
    ]
