# Generated by Django 4.2.7 on 2026-05-22 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS "chat_chatroom" (
                        "id" bigserial NOT NULL PRIMARY KEY,
                        "name" varchar(255) NULL,
                        "room_type" varchar(20) NOT NULL DEFAULT 'group',
                        "created_at" timestamptz NOT NULL,
                        "workspace_id" bigint NULL
                            REFERENCES "workspaces_workspace" ("id")
                            DEFERRABLE INITIALLY DEFERRED
                    );
                    CREATE TABLE IF NOT EXISTS "chat_chatroom_participants" (
                        "id" bigserial NOT NULL PRIMARY KEY,
                        "chatroom_id" bigint NOT NULL
                            REFERENCES "chat_chatroom" ("id")
                            DEFERRABLE INITIALLY DEFERRED,
                        "user_id" bigint NOT NULL
                            REFERENCES "accounts_user" ("id")
                            DEFERRABLE INITIALLY DEFERRED,
                        UNIQUE ("chatroom_id", "user_id")
                    );
                    """,
                    reverse_sql=(
                        'DROP TABLE IF EXISTS "chat_chatroom_participants";'
                        'DROP TABLE IF EXISTS "chat_chatroom";'
                    ),
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ChatRoom',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, max_length=255, null=True)),
                        ('room_type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('workspace', 'Workspace')], default='group', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
                        ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='workspaces.workspace')),
                    ],
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='channelmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='channelmembership',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channelmembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='message',
            name='direct_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='ChannelMembership',
        ),
        migrations.DeleteModel(
            name='DirectMessage',
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
            preserve_default=False,
        ),
    ]
