# Generated by Django 4.2.7 on 2026-05-22 21:38
# Patched: single SeparateDatabaseAndState handles all operations idempotently.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # ── Database side: all DDL is idempotent via IF (NOT) EXISTS ──────
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    -- Drop old tables from 0001 that are being replaced.
                    -- CASCADE handles FK references safely.
                    DROP TABLE IF EXISTS "chat_channelmembership" CASCADE;
                    DROP TABLE IF EXISTS "chat_channel_members"  CASCADE;
                    DROP TABLE IF EXISTS "chat_channel"          CASCADE;
                    DROP TABLE IF EXISTS "chat_directmessage_participants" CASCADE;
                    DROP TABLE IF EXISTS "chat_directmessage"    CASCADE;
                    DROP TABLE IF EXISTS "chat_messagereaction"  CASCADE;

                    -- Create ChatRoom and its M2M through table (IF NOT EXISTS).
                    CREATE TABLE IF NOT EXISTS "chat_chatroom" (
                        "id"           bigserial    NOT NULL PRIMARY KEY,
                        "name"         varchar(255) NULL,
                        "room_type"    varchar(20)  NOT NULL DEFAULT 'group',
                        "created_at"   timestamptz  NOT NULL DEFAULT now(),
                        "workspace_id" bigint       NULL
                            REFERENCES "workspaces_workspace" ("id")
                            DEFERRABLE INITIALLY DEFERRED
                    );
                    CREATE TABLE IF NOT EXISTS "chat_chatroom_participants" (
                        "id"          bigserial NOT NULL PRIMARY KEY,
                        "chatroom_id" bigint    NOT NULL
                            REFERENCES "chat_chatroom"   ("id") DEFERRABLE INITIALLY DEFERRED,
                        "user_id"     bigint    NOT NULL
                            REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                        UNIQUE ("chatroom_id", "user_id")
                    );

                    -- Remove old columns from chat_message that belonged to the
                    -- old Channel / DirectMessage / MessageReaction models.
                    ALTER TABLE chat_message DROP COLUMN IF EXISTS channel_id;
                    ALTER TABLE chat_message DROP COLUMN IF EXISTS direct_message_id;
                    ALTER TABLE chat_message DROP COLUMN IF EXISTS reply_to_id;
                    ALTER TABLE chat_message DROP COLUMN IF EXISTS updated_at;
                    ALTER TABLE chat_message DROP COLUMN IF EXISTS user_id;

                    -- Add new columns (IF NOT EXISTS keeps this idempotent).
                    ALTER TABLE chat_message
                        ADD COLUMN IF NOT EXISTS is_read boolean NOT NULL DEFAULT false;

                    ALTER TABLE chat_message
                        ADD COLUMN IF NOT EXISTS sender_id bigint NOT NULL DEFAULT 1
                            REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;

                    ALTER TABLE chat_message
                        ADD COLUMN IF NOT EXISTS room_id bigint NOT NULL DEFAULT 1
                            REFERENCES "chat_chatroom" ("id") DEFERRABLE INITIALLY DEFERRED;
                    """,
                    reverse_sql=(
                        'DROP TABLE IF EXISTS "chat_chatroom_participants";'
                        'DROP TABLE IF EXISTS "chat_chatroom";'
                    ),
                ),
            ],

            # ── State side: original operations so Django's ORM state is correct ──
            state_operations=[
                migrations.CreateModel(
                    name='ChatRoom',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(blank=True, max_length=255, null=True)),
                        ('room_type', models.CharField(
                            choices=[('private', 'Private'), ('group', 'Group'), ('workspace', 'Workspace')],
                            default='group', max_length=20,
                        )),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
                        ('workspace', models.ForeignKey(
                            blank=True, null=True,
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name='chat_rooms',
                            to='workspaces.workspace',
                        )),
                    ],
                ),
                migrations.AlterUniqueTogether(name='channelmembership', unique_together=None),
                migrations.RemoveField(model_name='channelmembership', name='channel'),
                migrations.RemoveField(model_name='channelmembership', name='user'),
                migrations.RemoveField(model_name='directmessage', name='participants'),
                migrations.RemoveField(model_name='messagereaction', name='message'),
                migrations.RemoveField(model_name='messagereaction', name='user'),
                migrations.AlterModelOptions(name='message', options={'ordering': ['created_at']}),
                migrations.RemoveField(model_name='message', name='channel'),
                migrations.RemoveField(model_name='message', name='direct_message'),
                migrations.RemoveField(model_name='message', name='reply_to'),
                migrations.RemoveField(model_name='message', name='updated_at'),
                migrations.RemoveField(model_name='message', name='user'),
                migrations.AddField(
                    model_name='message',
                    name='is_read',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='message',
                    name='sender',
                    field=models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sent_messages',
                        to=settings.AUTH_USER_MODEL,
                    ),
                    preserve_default=False,
                ),
                migrations.DeleteModel(name='Channel'),
                migrations.DeleteModel(name='ChannelMembership'),
                migrations.DeleteModel(name='DirectMessage'),
                migrations.DeleteModel(name='MessageReaction'),
                migrations.AddField(
                    model_name='message',
                    name='room',
                    field=models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to='chat.chatroom',
                    ),
                    preserve_default=False,
                ),
            ],
        ),
    ]
